import type { Metadata } from "next";
import { Nothing_You_Could_Do, Montserrat, Cormorant } from "next/font/google";

const nothing = Nothing_You_Could_Do({ subsets: ["latin"], weight: "400" });
const montserrat = Montserrat({ subsets: ["cyrillic", "latin"] });
const cormorant = Cormorant({ subsets: ["cyrillic", "latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body className={nothing.className}>{children}</body>
		</html>
	);
}
