import type { Metadata } from "next";
import { Nothing_You_Could_Do, Montserrat, Cormorant } from "next/font/google";
import "./globals.css";

const nothing = Nothing_You_Could_Do({ weight: "400" });
const montserrat = Montserrat();
const cormorant = Cormorant();

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body className={nothing.className}>{children}</body>
		</html>
	);
}
